#! /usr/bin/env bash

# Install script.

# Parameters.
FILE_DIR="files"
ENC_SUFFIX=".encrypted"
STORE_DIR=".linux-setup-store"

# Files installed in a directory other than ${HOME}.
# Keys are the file names, values are the directories.
declare -A nonhomefiles
nonhomefiles["config"]="${HOME}/.ssh"

# Manage custom file permissions.
chmod 600 files/config.encrypted
chmod 600 files/.pypirc.encrypted

# Main code ##########################################################

# Handle encrypted files -------------------------
# Get list of encrypted files.
enc_files=$(find ${FILE_DIR} -type f -name "*${ENC_SUFFIX}")

# Decrypt any encrypted files.
for file in ${enc_files}; do
	# Build output name for decrypted file.
	out_file=${FILE_DIR}/$(basename --suffix=${ENC_SUFFIX} ${file})

	# Decrypt file (if it hasn't already been decrypted).
	echo -n "Decrypting ${file} to ${out_file}."
	overwrite="y"
	if [[ -r ${out_file} ]] && [[ -f ${out_file} ]]; then
		echo -n "..decrypted file already exists. Overwrite (y/n)? "
		read overwrite
	fi

	if [[ "${overwrite}" =~ ^y|Y ]]; then
		echo -e "\nYou may need to enter your GPG key passphrase."
		# Decrypt file.
		gpg2 --yes --out ${out_file} --decrypt ${file}
		# Fix permissions (assumes encrypted file has correct permissions)
		chmod --reference=${file} ${out_file}
		
	fi
done

# Link files -------------------------------------
# Get file list (excluding encrypted files).
#file_list=$(ls -A ${FILE_DIR}/ --ignore="*${ENC_SUFFIX}")
file_list=$(find ${FILE_DIR}/ -mindepth 1 -maxdepth 1 \( -type f -o -type d \) \( ! -name "*${ENC_SUFFIX}" \) -printf "%f\n")

# Loop over files.
for file in ${file_list}; do
	# Get absolute path to file.
	afile=$(realpath ${FILE_DIR}/${file})

	# Get destination for symbolic link.
	if [[ -z ${nonhomefiles[${file}]} ]]; then
		dest=${HOME}/${file}
	else
		dest=${nonhomefiles[${file}]}/${file}
	fi

	# Link each one to its proper location; check for existence of
	# original files. If they are present, move them to a temp directory
	# for storage. The uninstall script will remove the symlinks and
	# restore the original files.
	echo "Setting up ${dest}."

	# Check if file or symlink already exists.
	if [[ -L ${dest} ]]; then
		# If symlink exists, just delete it.
		echo -e "\tDeleting old symbolic link ${dest}."
		rm ${dest}
	elif [[ -f ${dest} ]] || [[ -d ${dest} ]]; then
		# If file already exists, move to ~/${STORE_DIR}.
		if [[ -e ${STORE_DIR} ]] && [[ ! -d ${STORE_DIR} ]]; then
			echo -e "\tError: ${STORE_DIR} exists and is not a directory."
			exit 3
		elif [[ ! -e ${STORE_DIR} ]]; then
			echo -e "\tCreating directory ${STORE_DIR}."
			mkdir -p ${STORE_DIR}
		fi
		echo -e "\tMoving file ${dest} to ${STORE_DIR}."
		mv ${dest} ${STORE_DIR}
	fi
	
	# Symlink file.
	echo -e "\tLinking ${afile} to ${dest}."
	ln -s ${afile} ${dest}

done


